<div id="timesheet-mainframe">

<!-- some default values -->
<?php
$today = date("Y-m-d");
$currenttime = date("H:i");
?>

<!-- Mainframe Header -->
    <div id="timesheet-header"  class="timesheet-mainframesection">
		Timesheet for <div id="timesheet-header-selectionbox"> </div> 
	    <div class="timesheet-header-itembox">
			<button type="button" id="timesheet-report-signed" class="timesheet-button"><span class='icon-logout timesheet-header-button-icon'></span>Sign-off/Sign-on</button>
		</div>
	</div>

<!-- Mainframe Addform -->
	<div id="timesheet-addform"  class="timesheet-mainframesection">
		
    	<form id="timesheet-newrecord"  class="timesheet-addform">
        	<div class="timesheet-formitem timesheet-formheader">ADD</div>
            <div class="timesheet-formitem">
                <label for="timesheet-newrecord-date" class="timesheet-label" >Date
                <input type="date" name="date" id="timesheet-newrecord-date" value="<?php echo $today ?>" max="<?php echo $today ?>" class="timesheet-timebox"></label>
            </div>
            <div class="timesheet-formitem">
                <label for="timesheet-newrecord-starttime" class="timesheet-label" >Start Time
                <input type="time" name="starttime" id="timesheet-newrecord-starttime" value="00:00" class="timesheet-timebox"></label>
            </div>
            <div class="timesheet-formitem">
                <label for="timesheet-newrecord-endtime" class="timesheet-label" >End Time
                <input type="time" name="endtime" id="timesheet-newrecord-endtime" value="<?php echo $currenttime ?>" class=" timesheet-timebox"></label>
            </div>
            <div class="timesheet-formitem">
                <label for="timesheet-newrecord-breaktime" class="timesheet-label" >Break
                <input type="time" name="breaktime" id="timesheet-newrecord-breaktime" value="00:00" class="timesheet-timebox"></label>
            </div>
            <div class="timesheet-formitem">
                <label for="timesheet-newrecord-description" class="timesheet-label" >Description
                <input type="text" name="description" id="timesheet-newrecord-description" value="" class="timesheet-textbox"></label>
            </div>
			      <div class="timesheet-formitem">
                <label for="timesheet-newrecord-project" class="timesheet-label" >Assigned Project
                <div id="timesheet-newrecord-projectselectionbox"> </div> </label>
            </div>
            <div class="timesheet-formitem">
                <button type="button" id="timesheet-newrecord-submit" class="timesheet-button">
				    <span class='icon-confirm timesheet-button-icon'></span>Submit</button>
            </div>
            <div class="timesheet-formitem">
                <button type="button" id="timesheet-newrecord-refresh" class="timesheet-button">
				    <span class='icon-history timesheet-button-icon'></span>Refresh</button>
            </div>
        </form>
		
	</div>
	
<!-- Mainframe Content -->
	<div id="timesheet-content"  class="timesheet-mainframesection">
		
		<!-- report bar chart -->   
		<div id="timesheet-record-recordgraph">
			<canvas id="timesheet-record-recordgraph-chart"></canvas>
		</div> 
		
		
		<!-- Record Table-->
		<div class="timesheet-table">
			
			<div id="timesheet-report-summary">
				<!-- autogenerated content -->
			</div>
			
			<!-- record table header -->
			<div class="timesheet-tableheader">
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-time"> Date </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-time"> Start Time </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-time"> End Time </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-time"> Break </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-time"> Total Time </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-modify"> </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-long"> Description </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-long"> Project </div>
			</div>
			<div id="timesheet-report-content">
				<!-- autogenerated content -->
			</div>
			
		</div>
		
    </div>
	
<!-- dialog edit entry-->  
	
<div id="dialog-modify-record" title="Modify Record" class='hidden'>
  <form>
    <fieldset >
    	<div>
    		<label for="timesheet-dialog-date">Date
        	<input type="date" name="startdate" id="timesheet-dialog-startdate" value="" max="<?php echo $today ?>" class="timesheet-dialog-entrybox"></label>
            <label for="timesheet-dialog-starttime">Start Time</label>
            <input type="time" name="starttime" id="timesheet-dialog-starttime" value="" class="timesheet-dialog-entrybox"></label>
         </div><div>
            <label for="timesheet-dialog-endtime">End Time
            <input type="time" name="endtime" id="timesheet-dialog-endtime" value="" class="timesheet-dialog-entrybox"> </label> 
            <label for="timesheet-dialog-breaktime">Break Time
            <input type="time" name="endtime" id="timesheet-dialog-breaktime" value="" class="timesheet-dialog-entrybox"> </label> 
        </div>   
        <label for="timesheet-dialog-description">Description
      		<textarea  style='vertical-align: middle;width:300px;' name="description" id="timesheet-dialog-description" cols="40" rows="5" value=""  class="timesheet-dialog-entrybox"></textarea>
	  </label>
 		<div class="timesheet-dialog-itembox">
                <label for="timesheet-dialog-project">Assigned Project
                <div id="timesheet-dialog-projectselectionbox"> </div> </label>
          </div>
	  <div>  
            <label for="timesheet-dialog-unpayedoverhours">Unpayed Overhours
            <input type="checkbox" name="unpayedoverhours" id="timesheet-dialog-unpayedoverhours" value="" class="timesheet-dialog-entrybox"> </label>
        </div>
      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
  </form>
</div>   
    
</div>
