<div id="timesheet-content">

<!-- some default values -->
<?php
$today = date("Y-m-d");
$currenttime = date("H:i");
?>

<!-- Header -->
    <div id="timesheet-header">
    	Header
    </div>

<!-- new record bar -->
	<form oninput="timesheet-newrecord-worktime.value=timesheet-newrecord-starttime.value">
	<div id="timesheet-newrecord" class="form-row">	
    	<div class="timesheet-newrecord-itembox">
        	<label for="timesheet-newrecord-date">Date</label>
        	<input type="date" name="date" id="timesheet-newrecord-date" value="<?php echo $today ?>" max="<?php echo $today ?>" class="timesheet-newrecord-entrybox">
        </div>
        <div class="timesheet-newrecord-itembox">
            <label for="timesheet-newrecord-starttime">Start Time</label>
        	<input type="time" name="starttime" id="timesheet-newrecord-starttime" value="10:00" class="timesheet-newrecord-entrybox">
        </div>
        <div class="timesheet-newrecord-itembox">
            <label for="timesheet-newrecord-endtime">End Time</label>
        	<input type="time" name="endtime" id="timesheet-newrecord-endtime" value="<?php echo $currenttime ?>" class=" timesheet-newrecord-entrybox">
        </div>
        <div class="timesheet-newrecord-itembox">
            <label for="timesheet-newrecord-breaktime">Break Duration</label>
        	<input type="time" name="breaktime" id="timesheet-newrecord-breaktime" value="00:30" class="timesheet-newrecord-entrybox">
        </div>
        <div class="timesheet-newrecord-itembox">
            <label for="timesheet-newrecord-worktime">Work Duration</label>
        	<output type="time" name="worktime" id="timesheet-newrecord-worktime" class="timesheet-newrecord-entrybox">00:00</output>
        </div>
        <div class="timesheet-newrecord-itembox">
        	<button type="button" id="submit" class="timesheet-newrecord-entrybox">Submit</button>
		</div>
        <div class="timesheet-newrecord-itembox">
        	<button type="button" id="refresh" class="timesheet-newrecord-entrybox">Refresh</button>
		</div>
	</div>
	</form>    
<!-- generated record table -->
    <div id="timesheet-record-table">
    	<!-- record table header -->
        <div id="timesheet-record-table-header">
            <div class="timesheet-record-table-header-cell"> Date </div>
            <div class="timesheet-record-table-header-cell"> Start Time </div>
            <div class="timesheet-record-table-header-cell"> End Time </div>
            <div class="timesheet-record-table-header-cell"> Break Time </div>
            <div class="timesheet-record-table-header-cell"> Working Duration </div>
        </div>
        <div id="timesheet-record-table-content">
            <!-- autogenerated content -->
        </div>
	</div>
    
<!-- dialog edit or manual entry-->   
<div id="dialog-modify-record" title="Modify Record" class='hidden'>
  <form>
    <fieldset >
    	<div>
    		<label for="timesheet-dialog-date">Date</label>
        	<input type="date" name="startdate" id="timesheet-dialog-startdate" value="" max="<?php echo $today ?>" class="timesheet-dialog-entrybox">
            <label for="timesheet-dialog-starttime">Start Time</label>
            <input type="time" name="starttime" id="timesheet-dialog-starttime" value="" class="timesheet-dialog-entrybox">
         </div><div>
            <label for="timesheet-dialog-endtime">End Time</label>
            <input type="time" name="endtime" id="timesheet-dialog-endtime" value="" class="timesheet-dialog-entrybox">  
            <label for="timesheet-dialog-breaktime">Break Time</label>
            <input type="time" name="endtime" id="timesheet-dialog-breaktime" value="" class="timesheet-dialog-entrybox">  
        </div>   
        <label for="timesheet-dialog-description">Description</label>
      <textarea  style='vertical-align: middle;width:300px;' name="description" id="timesheet-dialog-description" cols="40" rows="5" value=""  class="timesheet-dialog-entrybox"></textarea>
 
      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
  </form>
</div>   
    
</div>
