<div id="timesheet-content">

<!-- some default values -->
<?php
$today = date("Y-m-d");
$currenttime = date("H:i");
?>

<!-- Header -->
    <div id="timesheet-header"></div>

<!-- new project bar -->
    <form id="timesheet-newproject">
        <div id="timesheet-newproject-form">	
        	<div class="timesheet-newproject-itembox timesheet-newproject-label">
                ADD
            </div>
			<div class="timesheet-newproject-itembox">
                <label for="timesheet-newproject-name">Name
                	<input type="text" name="name" id="timesheet-newproject-name" value="" class="timesheet-newproject-entrybox">
				</label>
            </div>
			<div class="timesheet-newproject-itembox">
				<label for="timesheet-newproject-parentselection">Parent Project
                	<div id="timesheet-newproject-parentselection"> </div> 
				</label>
            </div>
			<div class="timesheet-newproject-itembox">
                <label for="timesheet-newproject-description">Description
                <input type="text" name="description" id="timesheet-newproject-description" value="" class="timesheet-newproject-entrybox"></label>
            </div>
            <div class="timesheet-newproject-itembox">
                <button type="button" id="timesheet-newproject-submit" class="timesheet-newproject-entrybox timesheet-button"><span class='icon-confirm timesheet-newproject-button-icon'></span>Submit</button>
            </div>
            <div class="timesheet-newproject-itembox">
                <button type="button" id="timesheet-newproject-refresh" class="timesheet-newproject-entrybox timesheet-button"><span class='icon-history timesheet-newproject-button-icon'></span>Refresh</button>
            </div>
        </div>
     </form>
	
<!-- generated project table -->
    <div id="timesheet-projects">
           <div id="timesheet-projects-summary">
            <!-- autogenerated content -->
        </div>
    	<!-- project table header -->
        <div id="timesheet-projects-header">
            <div class="timesheet-projects-header-cell timesheet-report-column-name"> Name </div>
            <div class="timesheet-projects-header-cell timesheet-report-column-parent"> Parent Project </div>
            <div class="timesheet-projects-header-cell timesheet-report-column-duration"> Total Time </div>
            <div class="timesheet-projects-header-cell timesheet-report-column-modify"> </div>
            <div class="timesheet-projects-header-cell timesheet-report-column-description"> Description </div>
        </div>
        <div id="timesheet-projects-content">
            <!-- autogenerated content -->
        </div>
	</div>

</div>
