<div id="timesheet-mainframe">

<!-- Header -->
    <div id="timesheet-header" class="timesheet-mainframesection"></div>

<!-- Mainframe Addform -->
	<div id="timesheet-addform"  class="timesheet-mainframesection">
		
		<form id="timesheet-newproject" class="timesheet-addform">
				<div class="timesheet-formitem timesheet-formheader">ADD</div>
				<div class="timesheet-formitem">
					<label for="timesheet-newproject-name" class="timesheet-label">Name
					<input type="text" name="name" id="timesheet-newproject-name" value="" class="timesheet-textbox"></label>
				</div>
				<div class="timesheet-formitem">
					<label for="timesheet-newproject-parentselection"  class="timesheet-label" >Parent Project
					<div id="timesheet-newproject-parentselection"> </div> </label>
				</div>
				<div class="timesheet-formitem">
					<label for="timesheet-newproject-description"  class="timesheet-label" >Description
					<input type="text" name="description" id="timesheet-newproject-description" value="" class="timesheet-textbox"></label>
				</div>
				<div class="timesheet-formitem">
					<button type="button" id="timesheet-newproject-submit" class="timesheet-button">
						<span class='icon-confirm timesheet-button-icon'></span>Submit</button>
				</div>
				<div class="timesheet-formitem">
					<button type="button" id="timesheet-newproject-refresh" class="timesheet-button">
					<span class='icon-history timesheet-button-icon'></span>Refresh</button>
				</div>
		 </form>
		
	</div>
	
<!-- Mainframe Content -->
	<div id="timesheet-content"  class="timesheet-mainframesection">
		
<!-- Project Table -->
		<div class="timesheet-table">
			
			<!-- project table header -->
			<div class="timesheet-tableheader">
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-short"> </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-long"> Name </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-long"> Description </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-time"> Time Planned</div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-time"> Time Spend </div>
				<div class="timesheet-tableheader-cell timesheet-tablecolumn-modify"> </div>
			</div>

			<div id="timesheet-projects-content">
				<!-- autogenerated content -->
			</div>
		
		</div>
		
	</div>
</div>